In [3]:
"""
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
train_data_path = r"C:\house_price_prediction\data\train.csv"
test_data_path = r"C:\house_price_prediction\data\test.csv"

df_train = pd.read_csv(train_data_path)
df_test = pd.read_csv(test_data_path)

print("Shape of df_train: ", df_train.shape)
print("Shape of df_test: ", df_test.shape)

Shape of df_train:  (35000, 30)
Shape of df_test:  (7500, 30)

In [5]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [6]:
df_train.head()

,property_id,city,locality,locality_tier,property_type,bhk,bathrooms,balconies,built_up_area,carpet_area,floor_number,total_floors,floor_category,facing,furnishing_status,property_age,parking_spaces,security_score,gym_available,swimming_pool,power_backup,lift_available,maintenance_fee_monthly,distance_to_city_center_km,distance_to_metro_km,nearby_schools,nearby_hospitals,transaction_type,price_in_lakhs,price_category
0,PROP-045251,Mumbai,Bandra,Premium,Studio,1,1,0,526,454,0,5,Ground,North-East,Fully Furnished,10,1,7.2,1,1,1,0,5388,10.1,8.1,2,5,Resale,69.01,Low
1,PROP-037124,Bangalore,Whitefield,Standard,Villa,3,3,1,1833,1563,26,27,Top (20+),South,Unfurnished,1,0,8.1,1,1,1,1,5916,11.2,2.6,2,1,Resale,153.72,Low
2,PROP-017296,Mumbai,Powai,Standard,Independent House,3,3,1,1732,1452,5,6,Mid (5-9),North,Semi-Furnished,3,3,5.8,0,0,0,1,3166,10.3,2.4,3,2,New,122.76,Low
3,PROP-031278,Bangalore,Electronic City,Standard,Studio,1,2,0,447,362,4,5,Low (1-4),South-West,Semi-Furnished,8,1,5.1,0,0,1,1,1776,10.0,2.4,0,1,Resale,20.80,Low
4,PROP-034818,Mumbai,Thane,Affordable,Villa,4,5,0,2276,1944,1,2,Low (1-4),West,Fully Furnished,3,4,8.2,1,0,1,0,4667,23.5,0.6,3,0,Resale,177.95,Low

In [7]:
df_test.head()

,property_id,city,locality,locality_tier,property_type,bhk,bathrooms,balconies,built_up_area,carpet_area,floor_number,total_floors,floor_category,facing,furnishing_status,property_age,parking_spaces,security_score,gym_available,swimming_pool,power_backup,lift_available,maintenance_fee_monthly,distance_to_city_center_km,distance_to_metro_km,nearby_schools,nearby_hospitals,transaction_type,price_in_lakhs,price_category
0,PROP-034581,Delhi,South Delhi,Premium,Row House,4,4,0,1688,1362,11,16,High (10-19),North-East,Fully Furnished,8,3,5.7,1,0,1,1,5115,4.1,2.0,0,1,Resale,210.74,High
1,PROP-035680,Mumbai,Andheri,Standard,Apartment,3,3,1,1489,1194,4,11,Low (1-4),South,Fully Furnished,0,0,3.6,0,0,0,1,2605,11.3,0.9,4,2,Resale,88.69,Low
2,PROP-010901,Bangalore,Electronic City,Standard,Villa,4,3,2,2143,1746,8,9,Mid (5-9),South-East,Semi-Furnished,13,5,6.4,1,0,1,1,4875,11.6,0.2,4,2,Resale,215.20,High
3,PROP-019028,Mumbai,Bandra,Premium,Independent House,4,5,1,2230,1916,9,11,Mid (5-9),North-East,Semi-Furnished,4,1,6.2,1,0,1,1,4771,5.6,4.0,7,4,Resale,351.27,High
4,PROP-031670,Mumbai,Thane,Affordable,Row House,4,5,3,1805,1514,13,19,High (10-19),North,Fully Furnished,4,3,5.0,0,0,1,1,2844,18.2,0.3,5,0,Resale,62.77,Low

KNOW YOUR DATA

city
locality
locality_tier
bhk
bathrooms
total_floors
facing
furnishing_status
property_age
parking_spaces
distance_to_city_center_km
security_score
power_backup
lift_available

In [8]:
df = pd.concat([df_train,df_test])
print("Shape of integrated Data/ df: ", df.shape)

Shape of integrated Data/ df:  (42500, 30)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42500 entries, 0 to 7499
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   property_id                 42500 non-null  object
 1   city                        42500 non-null  object
 2   locality                    42500 non-null  object
 3   locality_tier               42500 non-null  object
 4   property_type               42500 non-null  object
 5   bhk                         42500 non-null  int64
 6   bathrooms                   42500 non-null  int64
 7   balconies                   42500 non-null  int64
 8   built_up_area               42500 non-null  int64
 9   carpet_area                 42500 non-null  int64
 10  floor_number                42500 non-null  int64
 11  total_floors                42500 non-null  int64
 12  floor_category              42500 non-null  object
 13  facing                      42500 non-null  object
 14  furnishing_status           42500 non-null  object
 15  property_age                42500 non-null  int64
 16  parking_spaces              42500 non-null  int64
 17  security_score              42500 non-null  float64
 18  gym_available               42500 non-null  int64
 19  swimming_pool               42500 non-null  int64
 20  power_backup                42500 non-null  int64
 21  lift_available              42500 non-null  int64
 22  maintenance_fee_monthly     42500 non-null  int64
 23  distance_to_city_center_km  42500 non-null  float64
 24  distance_to_metro_km        42500 non-null  float64
 25  nearby_schools              42500 non-null  int64
 26  nearby_hospitals            42500 non-null  int64
 27  transaction_type            42500 non-null  object
 28  price_in_lakhs              42500 non-null  float64
 29  price_category              42500 non-null  object
dtypes: float64(4), int64(16), object(10)
memory usage: 10.1+ MB

In [11]:
int_features = df.select_dtypes(include=["int64"]).columns
print("Total number of integer features : ", int_features.shape[0])

print("Integer feature names : ", int_features.tolist())

Total number of integer features :  16
Integer feature names :  ['bhk', 'bathrooms', 'balconies', 'built_up_area', 'carpet_area', 'floor_number', 'total_floors', 'property_age', 'parking_spaces', 'gym_available', 'swimming_pool', 'power_backup', 'lift_available', 'maintenance_fee_monthly', 'nearby_schools', 'nearby_hospitals']

In [12]:
float_features = df.select_dtypes(include=["float64"]).columns
print("Total number of floating features : ", float_features.shape[0])

print("Floating feature names : ", float_features.tolist())

Total number of floating features :  4
Floating feature names :  ['security_score', 'distance_to_city_center_km', 'distance_to_metro_km', 'price_in_lakhs']

In [13]:
cat_features = df.select_dtypes(include=["object"]).columns
print("Total number of categorical features : ", cat_features.shape[0])

print("Categorical feature names : ", cat_features.tolist())

Total number of categorical features :  10
Categorical feature names :  ['property_id', 'city', 'locality', 'locality_tier', 'property_type', 'floor_category', 'facing', 'furnishing_status', 'transaction_type', 'price_category']

GET THE STATISTICAL INFORMATION OF NUMERICAL FEATURES

In [14]:
df.describe()

,bhk,bathrooms,balconies,built_up_area,carpet_area,floor_number,total_floors,property_age,parking_spaces,security_score,gym_available,swimming_pool,power_backup,lift_available,maintenance_fee_monthly,distance_to_city_center_km,distance_to_metro_km,nearby_schools,nearby_hospitals,price_in_lakhs
count,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.00000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000,42500.000000
mean,3.151906,3.364941,1.687529,1573.120447,1321.430659,9.330424,14.441153,6.514471,1.914471,5.998859,0.414565,0.299435,0.685341,0.84000,3982.915506,11.535231,2.506880,3.119012,1.900518,166.590556
std,1.215476,1.330047,1.234808,670.073735,564.079721,8.698671,8.813876,6.890443,1.449107,1.602914,0.492653,0.458016,0.464385,0.36661,1637.884326,5.449117,2.479329,1.899756,1.466388,104.501947
min,1.000000,1.000000,0.000000,300.000000,240.000000,0.000000,1.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.00000,500.000000,4.000000,0.100000,0.000000,0.000000,10.000000
25%,2.000000,2.000000,1.000000,1046.000000,878.000000,3.000000,8.000000,2.000000,1.000000,4.900000,0.000000,0.000000,0.000000,1.00000,2683.000000,6.800000,0.700000,2.000000,1.000000,86.070000
50%,3.000000,3.000000,2.000000,1586.000000,1328.500000,7.000000,13.000000,4.000000,2.000000,5.900000,0.000000,0.000000,1.000000,1.00000,3672.000000,11.000000,1.700000,3.000000,2.000000,147.900000
75%,4.000000,4.000000,3.000000,2131.250000,1785.000000,14.000000,18.000000,9.000000,3.000000,7.100000,1.000000,1.000000,1.000000,1.00000,5185.000000,14.300000,3.500000,4.000000,3.000000,226.692500
max,5.000000,6.000000,4.000000,3056.000000,2666.000000,39.000000,45.000000,40.000000,5.000000,10.000000,1.000000,1.000000,1.000000,1.00000,8859.000000,45.000000,15.000000,10.000000,8.000000,737.590000

In [15]:
df.describe().shape

(8, 20)